wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718093537.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      - 37
      4: 3.8.19
      5: 0.16.5
      8:
      - 4
      - 5
      13: darwin-arm64
end_mask_prob:
  desc: null
  value: 0.9
finish_update:
  desc: null
  value: 0.5
hidden_dim1:
  desc: null
  value: 128
hidden_dim2:
  desc: null
  value: 64
latent_dim:
  desc: null
  value: 8
lr:
  desc: null
  value: 0.0001
mask_prob_step:
  desc: null
  value: 20
num_epochs:
  desc: null
  value: 200
start_mask_prob:
  desc: null
  value: 0.1
