wandb_version: 1

end_mask_prob:
  value: 0.7
finish_update:
  value: 0.33
hidden_dim1:
  value: 32
hidden_dim2:
  value: 32
latent_dim:
  value: 32
lr:
  value: 0.0001
mask_prob_step:
  value: 10
num_epochs:
  value: 100
start_mask_prob:
  value: 0.5
