wandb_version: 1

end_mask_prob:
  value: 0.5
finish_update:
  value: 0.33
hidden_dim1:
  value: 64
hidden_dim2:
  value: 64
latent_dim:
  value: 16
lr:
  value: 0.0001
mask_prob_step:
  value: 5
num_epochs:
  value: 100
start_mask_prob:
  value: 0.1
