wandb_version: 1

end_mask_prob:
  value: 0.9
finish_update:
  value: 0.5
hidden_dim1:
  value: 128
hidden_dim2:
  value: 64
latent_dim:
  value: 8
lr:
  value: 0.0001
mask_prob_step:
  value: 20
num_epochs:
  value: 200
start_mask_prob:
  value: 0.1
