wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.19
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1718094044.0
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 23
      - 37
      - 62
      4: 3.8.19
      5: 0.16.5
      8:
      - 4
      - 5
      13: darwin-arm64
end_mask_prob:
  desc: null
  value: 0.7
finish_update:
  desc: null
  value: 0.33
hidden_dim1:
  desc: null
  value: 32
hidden_dim2:
  desc: null
  value: 32
latent_dim:
  desc: null
  value: 32
lr:
  desc: null
  value: 0.0001
mask_prob_step:
  desc: null
  value: 10
num_epochs:
  desc: null
  value: 100
start_mask_prob:
  desc: null
  value: 0.5
